### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Kun8018** [wuxiaolang/Visual_SLAM_Related_Research#1]
大佬在哪里读硕？有出国的计划吗

**Comment by wuxiaolang** [comment]
现在在东北大学（沈阳）读研，读博还没联系老师（能力太差，没人要）。

**Comment by Kun8018** [comment]
做的很用心了，我们老板现在也只发过一篇iros一篇icra

**Comment by sanduan168** [comment]
楼上的同学们研究SLAM的哪个方向哇？

**Comment by wangzhengboo** [comment]
要不然拉个群聊大家交流一下？

**Comment by DreamWaterFound** [comment]
> 现在在东北大学（沈阳）读研，读博还没联系老师（能力太差，没人要）。

大佬太谦虚了~~

**Comment by liming-jing** [comment]
东大小弟我服了，求抱大腿

**Comment by doolisty** [comment]
> 要不然拉个群聊大家交流一下？

大佬拉个群吧，可以进去讨论一下。。

**Comment by shenyanqing1105** [comment]
哇有群吗有群吗！！！(#^.^#)

**Comment by yuqJin** [comment]
大佬们有群了吗？研一新生瑟瑟发抖T。T

**Comment by minnib578** [comment]
大佬们有群吗？

**Comment by zhangshuoneu** [comment]
学长好啊，我本科在咱东大读的，测绘专业，现在在武汉大学读研（研一），转到SLAM方向了。看学长做了这么多详细的论文简介和列举，真的对我很有用，想必学长一定很优秀，在领域里有所建树了，现在学长是就业了吗。对了，学长是哪个专业的
