### ISSUE TITLE
拼写小错误

### ISSUE THREAD

**Issue by zhuhu00** [wuxiaolang/Visual_SLAM_Related_Research#2]
一遍遍的看了大佬的整理，然后在寻找自己喜欢的方向。发现大佬整理的真的太好了。希望有机会能和大佬多交流，我在南方科技大学机器人研究院读研一，想做SLAM，学习了一些关于视觉的东西，也做点激光的动作，但是目前课题没定。
你的在 https://github.com/wuxiaolang/Visual_SLAM_Related_Research#1-msakfusion  ，应该是Maskfusion？

**Comment by wuxiaolang** [comment]
嗯嗯对的，感谢提醒，下次更新时修改一下。欢迎交流。
wuyanminmax@gmail.com
